name: 'Sync Repo Access'
description: 'Sync Repo Access list with the users listed in a file'
branding:
  icon: "lock"
  color: "orange"
inputs:
  role:
    description: 'Role of the users to update'
    required: true
    default: 'write'
  filename:
    description: 'filename to read users from'
    required: true
    default: 'CONTRIBUTORS'
outputs:
  resultJson:
    description: "Table of updates in Json format"
    value: ${{steps.result.outputs.resultJson}}
runs:
  using: "composite"
  steps:

    - name: Install RepoHelper
      id: install-repo-helper
      shell: pwsh
      run: |
          # Install RepoHelper module
          $module = Get-Module -ListAvailable -Name RepoHelper
          if ($null -eq $module) {
            Install-Module -Name RepoHelper -Force -AllowPrerelease
          }
          Get-Module -Name RepoHelper -ListAvailable

    - name: Find File
      id: find-file
      shell: pwsh
      env:
        FileName: ${{inputs.fileName}}
      run: |
          # Find CONTRIBUTORS
          $itemPath = $env:FileName
          if($itemPath | Test-Path){
            $item = $itemPath | Get-Item
          }

          $itemPath = ".github" | Join-Path -ChildPath $env:FileName
          if($itemPath | Test-Path){
            $item = $itemPath | Get-Item
          }

          if($null -eq $item){
            throw "Could not find file $env:FileName"
          }

          $ret = $item.FullName

          "Found file $ret" | Write-Host

          echo "filePath=$ret" >> $env:GITHUB_ENV

    - name: Run Sync-RepoAccess
      shell: pwsh
      env:
        Role: ${{inputs.role}}
        GH_TOKEN: ${{ github.token }}
      run: |
          # Run Sync-RepoAccess

          Import-Module -Name RepoHelper

          #$result = Sync-RepoAccess -role $env:Role -FilePath $env:FilePath -WhatIf
          $result = @{}
          $result.user1 ='-'
          $result.user2 ='+'
          $result.user3 ='?'

          $resultJson = $result | ConvertTo-Json

          $resultJson | Out-String | Write-Host

          # echo "result= $resultJson" >> $env:GITHUB_ENV

          @"
          resultJson= $resultJson
          "@ | Out-File -Append $env:GITHUB_ENV

    - name: Result
      id: result
      shell: pwsh
      run: | 
          # Result
          echo "resultJson= $env:result" >> $env:GITHUB_ENV
          echo "resultJson= $env:result" >> $env:GITHUB_OUTPUT

    - name: Trace Results
      shell: pwsh
      run: |
          # Trace Result
          $resultJson | Out-String | Write-Host

          $result = $resultJson | ConvertFrom-Json
          $result | Out-String | Write-Host



