name: 'Sync Repo Access'
description: 'Sync Repo Access list with the users listed in a file'
branding:
  icon: "lock"
  color: "orange"
inputs:
  role:
    description: 'Role of the users to update'
    required: true
    default: 'write'
  filename:
    description: 'filename to read users from'
    required: true
    default: 'CONTRIBUTORS'
outputs:
  table-of-updates:
    description: "Table of updates"
    value: ${{steps.run-sync-repo-access.table-of-updates}}
runs:
  using: "composite"
  steps:
    - name: Run Sync-RepoAccess
      id: run-sync-repo-access
      shell: pwsh
      env:
        Role: ${{inputs.role}}
        FileName: ${{inputs.fileName}}
      run: |

          # Install RepoHelper module
          $module = Get-Module -ListAvailable -Name RepoHelper
          if ($null -eq $module) {
            Install-Module -Name RepoHelper -Force -AllowPrerelease
          }
          Import-Module -Name RepoHelper

          # Find CONTRIBUTORS
          $itemPath = $env:FileName
          if($itemPath | Test-Path){
            $item = $itemPath | Get-Item
          }

          $itemPath = ".github" | Join-Path -ChildPath $env:FileName
          if($itemPath | Test-Path){
            $item = $itemPath | Get-Item
          }

          if($null -eq $item){
            throw "Could not find file $env:FileName"
          }

          # Run Sync-RepoAccess
          $result = Sync-RepoAccess -role $env:Role -FilePath $item.FullName -WhatIf

          # Output to the default output for tracing
          $result| Out-String | Write-Host

          # Convert to Json for output parameter
          $resultJson = $result | ConvertTo-Json
          $resultJson | Out-String | Write-Host

          # Set output parameter
          echo "table-of-updates= $resultJson" >> $GITHUB_OUTPUT

          return 0

